<?php

use Illuminate\Database\Seeder;

class CarreraSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
DB::Table('carreras')->insert([[
	     'nivel_escolar'=>'L',
	     'clave_oficial'=>'LINF-1993-303 ','clave_cosnet'=>'A ','nombre_carrera'=>'LICENCIATURA EN INFORMÁTICA','nombre_reducido'=>'LIC.INFORMÁTICA','siglas'=>'L. INF.','fecha_inicio'=>'1995-08-01','fecha_termino'=>'9999-01-01','creditos_totales'=>438,'carga_maxima'=>68,'carga_minima'=>38,'area_academica'=>'110600' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'LINF-2004-303 ','clave_cosnet'=>'A ','nombre_carrera'=>'LICENCIATURA EN INFORMÁTICA','nombre_reducido'=>'LIC.INFORMÁTICA','siglas'=>'L. INF.','fecha_inicio'=>'2004-08-01','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>60,'carga_minima'=>32,'area_academica'=>'110600' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IIND-1993-297 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA INDUSTRIAL','nombre_reducido'=>'ING. INDUSTRIAL','siglas'=>'I. IND.','fecha_inicio'=>'1992-08-01','fecha_termino'=>'9999-01-01','creditos_totales'=>430,'carga_maxima'=>68,'carga_minima'=>38,'area_academica'=>'110300' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IIND-2004-297 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA INDUSTRIAL','nombre_reducido'=>'ING. INDUSTRIAL','siglas'=>'I. IND.','fecha_inicio'=>'2004-08-01','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>60,'carga_minima'=>32,'area_academica'=>'110300' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IIND-2010-227 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA INDUSTRIAL','nombre_reducido'=>'ING. INDUSTRIAL','siglas'=>'I. IND.','fecha_inicio'=>'2010-07-01','fecha_termino'=>'9999-01-01','creditos_totales'=>260,'carga_maxima'=>36,'carga_minima'=>22,'area_academica'=>'110300' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'LADM-1993-300 ','clave_cosnet'=>'A ','nombre_carrera'=>'LICENCIATURA EN ADMINISTRACIÓN','nombre_reducido'=>'LIC. EN ADMON.','siglas'=>'ADMON.','fecha_inicio'=>'1993-08-01','fecha_termino'=>'9999-01-01','creditos_totales'=>440,'carga_maxima'=>68,'carga_minima'=>38,'area_academica'=>'110700' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'LADM-2004-300 ','clave_cosnet'=>'A ','nombre_carrera'=>'LICENCIATURA EN ADMINISTRACIÓN','nombre_reducido'=>'LIC. EN ADMON.','siglas'=>'ADMON.','fecha_inicio'=>'2004-08-02','fecha_termino'=>'9999-01-01','creditos_totales'=>392,'carga_maxima'=>60,'carga_minima'=>32,'area_academica'=>'110700' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'LADM-2010-234 ','clave_cosnet'=>'A ','nombre_carrera'=>'LICENCIATURA EN ADMINISTRACIÓN','nombre_reducido'=>'LIC. EN ADMON.','siglas'=>'ADMON.','fecha_inicio'=>'2010-07-01','fecha_termino'=>'9999-01-01','creditos_totales'=>260,'carga_maxima'=>36,'carga_minima'=>22,'area_academica'=>'110700' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IIND-2004-297 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA INDUSTRIAL','nombre_reducido'=>'ING. INDUSTRIAL A DIST.','siglas'=>'I. IND.','fecha_inicio'=>'2009-01-09','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>60,'carga_minima'=>32,'area_academica'=>'110300' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IIND-2010-227 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA INDUSTRIAL','nombre_reducido'=>'ING. INDUSTRIAL A DIST.','siglas'=>'I.I.','fecha_inicio'=>'2011-01-12','fecha_termino'=>'9999-01-01','creditos_totales'=>260,'carga_maxima'=>48,'carga_minima'=>22,'area_academica'=>'110300' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IELE-1993-290 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA ELÉCTRICA','nombre_reducido'=>'ING. ELÉCTRICA','siglas'=>'I. ELE.','fecha_inicio'=>'1993-08-01','fecha_termino'=>'9999-01-01','creditos_totales'=>440,'carga_maxima'=>68,'carga_minima'=>38,'area_academica'=>'110500' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IELE-2008-290 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA ELÉCTRICA','nombre_reducido'=>'ING. ELÉCTRICA','siglas'=>'I. ELE.','fecha_inicio'=>'2008-08-08','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>60,'carga_minima'=>32,'area_academica'=>'110500' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IELE-2010-209 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA ELÉCTRICA','nombre_reducido'=>'ING. ELÉCTRICA','siglas'=>'I. ELE.','fecha_inicio'=>'2010-07-01','fecha_termino'=>'9999-01-01','creditos_totales'=>259,'carga_maxima'=>36,'carga_minima'=>22,'area_academica'=>'110500' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IELC-1993-292 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA ELECTRÓNICA','nombre_reducido'=>'ING. ELECTRÓNICA','siglas'=>'I. ELO.','fecha_inicio'=>'1992-08-01','fecha_termino'=>'9999-01-01','creditos_totales'=>440,'carga_maxima'=>68,'carga_minima'=>38,'area_academica'=>'110500' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IELC-2004-292 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA ELECTRÓNICA','nombre_reducido'=>'ING. ELECTRÓNICA','siglas'=>'I. ELO.','fecha_inicio'=>'2004-08-02','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>60,'carga_minima'=>32,'area_academica'=>'110500' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IELC-2010-211 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA ELECTRÓNICA','nombre_reducido'=>'ING. ELECTRÓNICA','siglas'=>'I. ELO.','fecha_inicio'=>'2010-07-01','fecha_termino'=>'9999-01-01','creditos_totales'=>260,'carga_maxima'=>36,'carga_minima'=>22,'area_academica'=>'110500' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IMEC-1993-298 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA MECÁNICA','nombre_reducido'=>'ING. MECÁNICA','siglas'=>'MEC.','fecha_inicio'=>'1992-08-01','fecha_termino'=>'9999-01-01','creditos_totales'=>444,'carga_maxima'=>68,'carga_minima'=>38,'area_academica'=>'110200' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IMEC-2005-298 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA MECÁNICA','nombre_reducido'=>'ING. MECÁNICA','siglas'=>'MEC.','fecha_inicio'=>'2005-08-22','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>60,'carga_minima'=>32,'area_academica'=>'110200' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IMEC-2010-228 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA MECÁNICA','nombre_reducido'=>'ING. MECÁNICA','siglas'=>'MEC.','fecha_inicio'=>'2010-07-01','fecha_termino'=>'9999-01-01','creditos_totales'=>260,'carga_maxima'=>36,'carga_minima'=>22,'area_academica'=>'110100' ,'area_id'=>1],
['nivel_escolar'=>'P','clave_oficial'=>'MPIM-2007-04 ','clave_cosnet'=>'A ','nombre_carrera'=>'MAESTRÍA EN INGENIERÍA MECÁNICA','nombre_reducido'=>'MAESTRÍA EN ING. MECÁNICA','siglas'=>'MIM','fecha_inicio'=>'2008-08-26','fecha_termino'=>'9999-01-01','creditos_totales'=>102,'carga_maxima'=>50,'carga_minima'=>32,'area_academica'=>'0 ' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'ISIC-1993-296 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA EN SISTEMAS COMPUTACIONALES','nombre_reducido'=>'ING. SIST. COMP','siglas'=>'SIST.','fecha_inicio'=>'1993-08-01','fecha_termino'=>'9999-01-01','creditos_totales'=>440,'carga_maxima'=>68,'carga_minima'=>38,'area_academica'=>'110600' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'ISIC-2004-296 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA EN SISTEMAS COMPUTACIONALES','nombre_reducido'=>'ING. SIST. COMP','siglas'=>'SIST.','fecha_inicio'=>'2004-08-02','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>60,'carga_minima'=>32,'area_academica'=>'110600' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'ISIC-2010-224 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA EN SISTEMAS COMPUTACIONALES','nombre_reducido'=>'ING. SIST. COMP','siglas'=>'SIST.','fecha_inicio'=>'2010-08-05','fecha_termino'=>'9999-01-01','creditos_totales'=>260,'carga_maxima'=>36,'carga_minima'=>22,'area_academica'=>'110600' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IGEM-2009-201 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA EN GESTIÓN EMPRESARIAL','nombre_reducido'=>'ING. EN GEST. EMP.','siglas'=>'IGE.','fecha_inicio'=>'2009-03-31','fecha_termino'=>'9999-01-01','creditos_totales'=>260,'carga_maxima'=>36,'carga_minima'=>22,'area_academica'=>'110700' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IMCT-2005-284 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA MECATRÓNICA','nombre_reducido'=>'ING. MECATRÓNICA','siglas'=>'MCT.','fecha_inicio'=>'2005-08-22','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>60,'carga_minima'=>32,'area_academica'=>'110500' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IMCT-2002-001 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA MECATRÓNICA','nombre_reducido'=>'ING. MECATRÓNICA','siglas'=>'I. M.','fecha_inicio'=>'2003-08-18','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>60,'carga_minima'=>32,'area_academica'=>'110500' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IMCT-2010-229 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA MECATRÓNICA','nombre_reducido'=>'ING. MECATRÓNICA','siglas'=>'MCT.','fecha_inicio'=>'2010-07-01','fecha_termino'=>'9999-01-01','creditos_totales'=>260,'carga_maxima'=>36,'carga_minima'=>22,'area_academica'=>'110500' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'LOLOP ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERIA EN INFORMATICA','nombre_reducido'=>'ING. EN INF.','siglas'=>'I. INF.','fecha_inicio'=>'2009-03-31','fecha_termino'=>'9999-01-01','creditos_totales'=>260,'carga_maxima'=>64,'carga_minima'=>32,'area_academica'=>'0 ' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'II-80-025 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA INDUSTRIAL EN PRODUCCIÓN','nombre_reducido'=>'ING. IND. EN PROD.','siglas'=>'I. I. P.','fecha_inicio'=>'2009-09-10','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>68,'carga_minima'=>38,'area_academica'=>'110300' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'II-80-025 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA INDUSTRIAL EN PRODUCCIÓN','nombre_reducido'=>'ING. IND. EN PROD.','siglas'=>'I. I. P.','fecha_inicio'=>'2009-09-10','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>68,'carga_minima'=>38,'area_academica'=>'110300' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'II-80-025 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA INDUSTRIAL EN PRODUCCIÓN','nombre_reducido'=>'ING. IND. EN PROD.','siglas'=>'I. I. P.','fecha_inicio'=>'2009-09-10','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>68,'carga_minima'=>38,'area_academica'=>'110300' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'ISIC-1990-266 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA EN SISTEMAS COMPUTACIONALES','nombre_reducido'=>'ING. EN SIST. COMP.','siglas'=>'I. S C.','fecha_inicio'=>'1900-01-01','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>70,'carga_minima'=>32,'area_academica'=>'110600' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'II-80-231 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA INDUSTRIAL EN ELECTRÓNICA','nombre_reducido'=>'ING. IND. EN ELEC.','siglas'=>'I. I. E.','fecha_inicio'=>'1900-01-01','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>58,'carga_minima'=>30,'area_academica'=>'110500' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'LT-77-030 ','clave_cosnet'=>'A ','nombre_carrera'=>'LICENCIATURA EN ADMINISTRACIÓN DE EMPRESAS TURÍSTICAS/ HOTELERÍA Y RESTAURANT','nombre_reducido'=>'LIC. EN ADMON. DE EMP. T.','siglas'=>'L.A.E.T.R.','fecha_inicio'=>'2009-10-05','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>65,'carga_minima'=>35,'area_academica'=>'110700' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'II-80-210 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA INDUSTRIAL MECÁNICA EN DISEÑO DE MANUFACTURA','nombre_reducido'=>'ING. IND. MEC. DISE. MANUF.','siglas'=>'I.I.M.D.M.','fecha_inicio'=>'2009-10-27','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>68,'carga_minima'=>38,'area_academica'=>'110200' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'LR-77-020 ','clave_cosnet'=>'A ','nombre_carrera'=>'LICENCIATURA EN RELACIONES INDUSTRIALES','nombre_reducido'=>'LIC. EN REL . IND.','siglas'=>'L.R.I.','fecha_inicio'=>'2009-10-05','fecha_termino'=>'9999-01-01','creditos_totales'=>380,'carga_maxima'=>65,'carga_minima'=>35,'area_academica'=>'110700' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'II-80-230 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA INDUSTRIAL EN ELÉCTRICA','nombre_reducido'=>'ING. IND. ELEC.','siglas'=>'II','fecha_inicio'=>'2009-10-09','fecha_termino'=>'9999-01-01','creditos_totales'=>380,'carga_maxima'=>85,'carga_minima'=>35,'area_academica'=>'110500' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'II-80-211 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA INDUSTRIAL MECÁNICA EN TÉRMICA','nombre_reducido'=>'ING. IND. MEC','siglas'=>'IIM','fecha_inicio'=>'1900-01-01','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>0,'carga_minima'=>0,'area_academica'=>'110200' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IS-78-120 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA EN SISTEMAS COMPUTACIONALES','nombre_reducido'=>'ING. SIST.COMP.','siglas'=>'ISC','fecha_inicio'=>'1900-01-01','fecha_termino'=>'9999-01-01','creditos_totales'=>380,'carga_maxima'=>388,'carga_minima'=>0,'area_academica'=>'110600' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'II-73-025 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA INDUSTRIAL EN PRODUCCIÓN','nombre_reducido'=>'ING. IND. EN PROD.','siglas'=>'I. I. P.','fecha_inicio'=>'2009-09-10','fecha_termino'=>'9999-01-01','creditos_totales'=>400,'carga_maxima'=>68,'carga_minima'=>38,'area_academica'=>'110300' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IS-80-160 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA EN SISTEMAS COMPUTACIONALES EN PROGRAMACIÓN','nombre_reducido'=>'ING. SIST.COMP. PROGR.','siglas'=>'ISCP','fecha_inicio'=>'1900-01-01','fecha_termino'=>'9999-01-01','creditos_totales'=>382,'carga_maxima'=>0,'carga_minima'=>0,'area_academica'=>'110600' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'IINF-2010-220 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA INFORMÁTICA','nombre_reducido'=>'ING. INFORMÁTICA','siglas'=>'I. INF.','fecha_inicio'=>'2010-08-02','fecha_termino'=>'9999-01-01','creditos_totales'=>260,'carga_maxima'=>36,'carga_minima'=>22,'area_academica'=>'110600' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'ISIC-2010-224 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA EN SISTEMAS COMPUTACIONALES','nombre_reducido'=>'ING. SIST. COMP A DIST.','siglas'=>'I.S.C.','fecha_inicio'=>'2011-01-13','fecha_termino'=>'9999-01-01','creditos_totales'=>260,'carga_maxima'=>36,'carga_minima'=>22,'area_academica'=>'110600' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'LR-77-020 ','clave_cosnet'=>'A ','nombre_carrera'=>'LICENCIATURA EN RELACIONES INDUSTRIALES','nombre_reducido'=>'LIC. REL. IND.','siglas'=>'LR','fecha_inicio'=>'1900-01-01','fecha_termino'=>'9999-01-01','creditos_totales'=>380,'carga_maxima'=>0,'carga_minima'=>0,'area_academica'=>'0 ' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'LTUR-2012-237 ','clave_cosnet'=>'A ','nombre_carrera'=>'LICENCIATURA EN TURISMO','nombre_reducido'=>'LIC. EN TURISMO','siglas'=>'LTUR','fecha_inicio'=>'2013-05-24','fecha_termino'=>'9999-01-01','creditos_totales'=>260,'carga_maxima'=>36,'carga_minima'=>22,'area_academica'=>'110700' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'TM-73-180 ','clave_cosnet'=>' ','nombre_carrera'=>'TÉCNICO EN MECÁNICA AUTOMOTRÍZ','nombre_reducido'=>'TECNICO EN CECANICA AUTOMOTRIZ','siglas'=>'TMA','fecha_inicio'=>'1900-01-01','fecha_termino'=>'9999-01-01','creditos_totales'=>0,'carga_maxima'=>0,'carga_minima'=>0,'area_academica'=>'0 ' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'LR-77-020 ','clave_cosnet'=>'A ','nombre_carrera'=>'LICENCIATURA EN RELACIONES INDUSTRIALES','nombre_reducido'=>'LIC. EN RELACIONES IND.','siglas'=>'L. R. I.','fecha_inicio'=>'1900-01-01','fecha_termino'=>'9999-01-01','creditos_totales'=>10,'carga_maxima'=>5,'carga_minima'=>7,'area_academica'=>'110700' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'II-73-010 ','clave_cosnet'=>'A ','nombre_carrera'=>'INGENIERÍA INDUSTRIAL EN ELECTRÓNICA','nombre_reducido'=>'II','siglas'=>'IIE','fecha_inicio'=>'1974-01-08','fecha_termino'=>'9999-01-01','creditos_totales'=>380,'carga_maxima'=>0,'carga_minima'=>0,'area_academica'=>'0 ' ,'area_id'=>1],
['nivel_escolar'=>'L','clave_oficial'=>'LR-77-020 ','clave_cosnet'=>'A ','nombre_carrera'=>'LICENCIATURA EN RELACIONES INDUSTRIALES','nombre_reducido'=>'LIC. RELACIONES INDUSTRIALES','siglas'=>'LR','fecha_inicio'=>'1900-01-01','fecha_termino'=>'9999-01-01','creditos_totales'=>10,'carga_maxima'=>10,'carga_minima'=>10,'area_academica'=>'0 ' ,'area_id'=>1]
]);
    }
}
